# 파일 업로드 상세설정
file: 
  filegrpName: 
    biz_logo:                             # 파일그룹_이름(기관로고)
      uploadPath: /biz_logo                # 업로드 경로
      uploadFileSize: 10                   # 업로드가능 파일사이즈(MB)
      uploadFileExtsn: [png,gif,jpg,jpeg]  # 업로드가능 확장자
      isThumbnail: true                    # 썸네일 생성여부
      thumbnailWidth: 150                  # 썸네일 너비
      thumbnailHeight: 150                 # 썸네일 높이
      downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    biz_photo:                            #기업이미지(미사용)
      uploadPath: /biz_photo 
      uploadFileSize: 10                    
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 480
      thumbnailHeight: 300
      downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    user_profile:                         # 프로필사진(미사용)
      uploadPath: /user_profile 
      uploadFileSize: 10                    
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 200
      thumbnailHeight: 200
      downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    contract:                             # 
      uploadPath: /contract 
      uploadFileSize: 10  
      downloadChecker: [login]                  
    bbs:                                  # 게시판
      uploadPath: /bbs
    ckEditor:                             # 에디터
      uploadPath: /ckEimg
      uploadFileSize: 5
      uploadFileExtsn: [jpg,png,jpeg,gif]
    biz_file:                             # 
      uploadPath: /biz_file
      downloadChecker: [login]
    thmbn_file:                           # 썸네일 파일(웹진)
      uploadPath: /thmbn_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 150
      thumbnailHeight: 150
      downloadChecker: [login]
    asgsysSrng_file:                      #   
      uploadPath: /asgsysSrng_file      
      uploadFileSize: 10
      downloadChecker: [login]
    site_logo:                            # 사이트로고
      uploadPath: /site_logo              
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
    banner_file:                          # 배너관리 이미지 파일
      uploadPath: /banner_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 150
      thumbnailHeight: 150    