# 파일 업로드 상세설정
file:
  filegrpName:
    biz_logo:                             # 파일그룹_이름(기관로고)
      uploadPath: /biz_logo                # 업로드 경로
      uploadFileSize: 10                   # 업로드가능 파일사이즈(MB)
      uploadFileExtsn: [png,gif,jpg,jpeg]  # 업로드가능 확장자
      #imageSize: [240X120]                 # 허용이미지 사이즈
      #isThumbnail: true                    # 썸네일 생성여부
      #thumbnailWidth: 150                  # 썸네일 너비
      #thumbnailHeight: 150                 # 썸네일 높이
      #downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    biz_photo:                            #기업이미지(미사용)
      uploadPath: /biz_photo
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 480
      thumbnailHeight: 300
      downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    user_profile:                         # 프로필사진(미사용)
      uploadPath: /user_profile
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 200
      thumbnailHeight: 200
      downloadChecker: [login]             # 다운로드가능 조건(로그인Y)
    contract:                             #
      uploadPath: /contract
      uploadFileSize: 60                   # 업로드가능 파일사이즈(MB)
      uploadFileTotalSize: 100             # (다중파일)업로드가능 총 파일사이즈(MB)
      uploadFileCnt: 2                     # (다중파일)업로드가능 파일 갯수
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    bbs:                                  # 게시판
      uploadPath: /bbs
    ckEditor:                             # 에디터
      uploadPath: /ckEimg
      uploadFileSize: 5
      uploadFileExtsn: [jpg,png,jpeg,gif]
    biz_file:                             #
      uploadPath: /biz_file
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
      downloadChecker: [login]
    thmbn_file:                           # 썸네일 파일(웹진)
      uploadPath: /thmbn_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
    asgsysSrng_file:                      #
      uploadPath: /asgsysSrng_file
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    site_logo:                            # 사이트로고
      uploadPath: /site_logo
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      #imageSize: [150X30,153X44]          # 허용이미지 사이즈
    banner_file:                          # 배너관리 이미지 파일
      uploadPath: /banner_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      imageSize: [600X300]                 # 허용이미지 사이즈
    helpdesk_file:                         # 헬프데스크 문의 파일
      uploadPath: /helpdesk_file
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileCnt: 5
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]             # 다운로드 가능 조건(로그인Y)
    expert_file:                           # 전문가 관련 파일
      uploadPath: /expert_file
      uploadFileSize: 10
      uploadFileCnt: 1
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    cnsnltng_file:                             #
      uploadPath: /cnsnltng_file
      downloadChecker: [login]
    cmt_bbs:                                  # 커뮤니티 게시판(환경동아리)
      uploadPath: /cmt_bbs
    wbzn_banner_file:                          # 배너관리(웹진) 이미지 파일
      uploadPath: /wbzn_banner_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      #imageSize: [1005X285]                 # 허용이미지 사이즈
    envtcher_thmbn_file:                           # 썸네일 파일(환경교육사 양성기관 현황)
      uploadPath: /envtcher_thmbn_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    eduIntrcn_file:                           # 교육소개 파일(교육프로그램 관리)
      uploadPath: /eduIntrcn_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    eduPhotoFile_file:                           # 교육사진 파일(교육프로그램 관리)
      uploadPath: /eduPhotoFile_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    dstnctnEduPhoto_file:                        # 우수성교육사진 (지정신청)
      uploadPath: /dstnctnEduPhoto_file
      uploadFileSize: 10
      uploadFileCnt: 3                           # (다중파일)업로드가능 파일 갯수
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
      #imageSize: [200X140]                       # 허용이미지 사이즈
    jntpurchsRprsImgFile:             # 공동구매 대표이미지
      uploadPath: /jntpurchs_rprs
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
    jntpurchsDtlImgFile:               # 공동구매 상세 이미지
      uploadPath: /jntpurchs_dtl
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileExtsn: [png,gif,jpg,jpeg]
    jntpurchsMapFile:                  # 공동구매 지도 파일
      uploadPath: /jntpurchs_map
      uploadFileSize: 100
      uploadFileExtsn: [pdf]
    jntpurchsEduPhotoFile:           # 공동구매 교육사진 파일
      uploadPath: /jntpurchs_edu_photo
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileExtsn: [png,gif,jpg,jpeg]
    cntnts_rprs_img_file:                 # 대표이미지(콘텐츠관리)
      uploadPath: /cntnts_rprs_img_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
    cntnts_atch_file:                     # 첨부파일(콘텐츠관리)
      uploadPath: /cntnts_atch_file
      uploadFileSize: 10
      uploadFileTotalSize: 100
    pcntst:                             # 공모관리
      uploadPath: /pcntst                # 업로드 경로
      uploadFileSize: 10                   # 업로드가능 파일사이즈(MB)
      uploadFileCnt: 5                     # (다중파일)업로드가능 파일 갯수
      uploadFileTotalSize: 50             # (다중파일)업로드가능 총 파일사이즈(MB)
    cntst_thmbn:
      uploadPath: /cntst_thmbn
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      downloadChecker: [ login ]
    cntst_atch:
      uploadPath: /cntst_atch
      downloadChecker: [ login ]
      uploadFileCnt: 5                     # (다중파일)업로드가능 파일 갯수      
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
    book_rprs_img_file:                 # 대표이미지(우수환경도서관리)
      uploadPath: /book_rprs_img_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
    book_atch_file:                     # 첨부파일(우수환경도서관리)
      uploadPath: /book_atch_file
      downloadChecker: [login]
    evnt_file:                            # 이벤트 파일
      uploadPath: /evnt_File
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileCnt: 5                     # (다중파일)업로드가능 파일 갯수
      uploadFileExtsn: [png,gif,jpg,jpeg]
    env_edu_rprs_img_file:                 # 대표이미지(우수환경교육 프로그램 관리)
      uploadPath: /env_edu_rprs_img_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    env_edu_atch_file:                     # 첨부파일(우수환경교육 프로그램 관리)
      uploadPath: /env_edu_atch_file
      downloadChecker: [login]
    inqry_file:
      uploadPath: /inqry_file
      uploadFileSize: 10
      uploadFileExtsn: [png,gif,jpg,jpeg]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    pltfom_imprvm_propsl_file:
      uploadPath: /pltfom_imprvm_propsl_file
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    aply_file_1:                             # 신청관리 > 신청정보 : 증빙서류1
      uploadPath: /aply_file_1           
      downloadChecker: [login]           
    aply_file_2:                             # 신청관리 > 신청정보 : 증빙서류2
      uploadPath: /aply_file_2           
      downloadChecker: [login]           
    aply_file_3:                             # 신청관리 > 신청정보 : 증빙서류3
      uploadPath: /aply_file_3           
      downloadChecker: [login]
    delvryAplyAtchFile:                         # 교부신청 첨부파일
      uploadPath: /delvry_aply_atch_file
      uploadFileSize: 10
      uploadFileTotalSize: 50
      downloadChecker: [login]
    envPrpsl_file:
      uploadPath: /envPrpsl_file
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    lctrDmnd_file:
      uploadPath: /lctrDmnd_file
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    bizRptMng_file:
      uploadPath: /bizRptMng_file             # 첨부파일(사업보고관리:증빙서류)
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    lendLogo_file:
      uploadPath: /lend_logo_file             # 대여 로고 파일
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      uploadFileTotalSize: 50
      uploadFileCnt: 1
    lend_file:
      uploadPath: /lend_file                  # 대여 첨부 파일             
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
    dsgnPrgrm_file:
      uploadPath: /dsgnPrgrm_file             # 지정프로그램 파일
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
      uploadFileTotalSize: 50
      uploadFileCnt: 5
    pdf_view_file:                              # pdfviewer용 파일
     uploadPath: /pdf_view_file
     uploadFileExtsn : [pdf]
    jntpurchsRvwfile:                           # 환경교육 교구 공동구매 후기 첨부파일
      uploadPath: /jntpurchs_rvw_file
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    cntst_aply_prdct:                           #공모전 신청
      uploadPath: /cntst_aply_prdct
      downloadChecker: [ login ]
      uploadFileCnt: 5                          # (다중파일)업로드가능 파일 갯수
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
    cmnty_logo:                                 #환경동아리 사진
      uploadPath: /cmnty_logo
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
      #imageSize: [240X120]
    cmntyPst_file:                              #환경동아리 게시글 첨부파일
      uploadPath: /cmntyPst_file
      #uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
      #uploadFileTotalSize: 50
      #uploadFileCnt: 5
    lendRvwfile:                           # 환경교육 교구 대여  후기 첨부파일
      uploadPath: /lend_rvw_file
      uploadFileSize: 10
      uploadFileTotalSize: 50
      uploadFileExtsn: [png,gif,jpg,jpeg]
      downloadChecker: [login]
    clclnDsctn_file:                             # 마이페이지 > 체험환경 > 정산관리 > 정산관리내역 탭 증빙서류 첨부파일
      uploadPath: /clclnDsctn_file           
      downloadChecker: [login]
    bsnsOperDta_file: # 콘텐츠 교구 > 사업운영 자료
      uploadPath: /bsnsOperDta_file
      uploadFileSize: 10
      uploadFileCnt: 5
      uploadFileToTalSize: 50
      uploadFileExtsn: [jpg,zip, jpeg, png, gif, hwp, doc, docx, xls, xlsx, pdf, txt, ppt, pptx]
    spcltyDta_file: # 콘텐츠 교구 > 전문 자료
      uploadPath: /spcltyDta_file
      uploadFileSize: 10
      uploadFileCnt: 5
      uploadFileToTalSize: 50
      uploadFileExtsn: [ jpg,zip, jpeg, png, gif, hwp, doc, docx, xls, xlsx, pdf, txt, ppt, pptx ]
    etcDta_file: # 콘텐츠 교구 > 기타 자료
      uploadPath: /etcDta_file
      uploadFileSize: 10
      uploadFileCnt: 5
      uploadFileToTalSize: 50
      uploadFileExtsn: [ jpg,zip, jpeg, png, gif, hwp, doc, docx, xls, xlsx, pdf, txt, ppt, pptx ]
    cntst_aply_schl:                           #공모전 신청(환경일기장신청)
      uploadPath: /cntst_aply_schl
      downloadChecker: [ login ]
      uploadFileCnt: 5                          # (다중파일)업로드가능 파일 갯수
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
    cntstThmbnFile:                             # 공모전 썸네일 이미지
      uploadPath: /cntst_thmbn
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif]        
    cntstAtchFile:                                # 공모전 첨부파일
      uploadPath: /cntst_atch
      uploadFileSize: 10
      uploadFileCnt: 5
      uploadFileToTalSize: 50
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]
    rprsImg_file: # 시설관리 > 대표 이미지
        uploadPath: /rprsImg_file
        uploadFileSize: 10
        uploadFileExtsn: [ png,gif,jpg,jpeg ]
    dtlImg_file: # 시설관리 > 상세 이미지
      uploadPath: /dtlImg_file
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
    gdnc_file: # 시설관리 > 안내자료
      uploadPath: /gdnc_file
      uploadFileSize: 10
      uploadFileExtsn: [ png,gif,jpg,jpeg ]
    eduInst_file: # 사회환경교육기업 첨부파일
      uploadPath: /eduInst_file
      uploadFileSize: 10
      uploadFileExtsn: [jpeg,jpg,png,gif,tif,tiff,hwp,hwpx,pdf,ppt,pptx,doc,docx,xls,xlsx,zip]