# 파일 업로드 상세설정
file: 
  filegrpName: 
    biz_logo:                             # 파일그룹_이름(기업로고이미지)
      uploadPath: /biz_logo                # 업로드 경로
      uploadFileSize: 10                   # 업로드가능 파일사이즈(MB)
      uploadFileExtsn: [png,gif,jpg,jpeg]  # 업로드가능 확장자
      isThumbnail: true                    # 썸네일 생성여부
      thumbnailWidth: 150                  # 썸네일 너비
      thumbnailHeight: 150                 # 썸네일 높이
    biz_photo:                            #기업이미지
      uploadPath: /biz_photo 
      uploadFileSize: 10                    
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 480
      thumbnailHeight: 300
    user_profile:                         #프로필사진(개인)
      uploadPath: /user_profile 
      uploadFileSize: 10                    
      uploadFileExtsn: [png,gif,jpg,jpeg]
      isThumbnail: true
      thumbnailWidth: 200
      thumbnailHeight: 200
    contract:
      uploadPath: /contract 
      uploadFileSize: 10                    
      uploadFileExtsn: [pdf]
    bbs:
      uploadPath: /bbs